name: Build Spec

on:
  push:
    branches-ignore:
      - 'temp/*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
      - 'support/v1.0.x'

jobs:

  build-spec:

    name: Build SSP Specification
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        submodules: recursive

    - name: List variables
      run: |
        [[ $GITHUB_REF_TYPE == "tag" ]] && REVNUMBER=${GITHUB_REF:11} || REVNUMBER=${GITHUB_SHA:0:7}
        echo GITHUB_SHA:      $GITHUB_SHA
        echo GITHUB_REF_TYPE: $GITHUB_REF_TYPE
        echo GITHUB_REF:      $GITHUB_REF
        echo REVNUMBER:       $REVNUMBER
        echo "REVNUMBER=$REVNUMBER" >> $GITHUB_ENV

    - name: Fetch XML Schema Schema
      run: wget https://www.w3.org/TR/xmlschema11-1/XMLSchema.xsd

    - name: Enable Annotations for Validation Errors and Warnings
      uses: korelstar/xmllint-problem-matcher@v1

    - name: Validate SSC Schema
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schema/SystemStructureCommon.xsd
        xml-schema-file: ./XMLSchema.xsd

    - name: Validate SSD Schema
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schema/SystemStructureDescription.xsd
        xml-schema-file: ./XMLSchema.xsd

    - name: Validate SSD11 Schema
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schema/SystemStructureDescription11.xsd
        xml-schema-file: ./XMLSchema.xsd

    - name: Validate SSV Schema
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schema/SystemStructureParameterValues.xsd
        xml-schema-file: ./XMLSchema.xsd

    - name: Validate SSM Schema
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schema/SystemStructureParameterMapping.xsd
        xml-schema-file: ./XMLSchema.xsd

    - name: Validate SSB Schema
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schema/SystemStructureSignalDictionary.xsd
        xml-schema-file: ./XMLSchema.xsd

    - name: Create build directory
      run: |
        mkdir -p build/schema
        mkdir -p build/images

    - name: Generate HTML
      uses: avattathil/asciidoctor-action@master
      with:
        program: "asciidoctor --destination-dir=build --backend=html5 --attribute=revnumber=${{env.REVNUMBER}} --attribute=revdate=$(date +%F) docs/index.adoc"

    - name: Replace ULRs
      run: |
        uv run theme/update_urls.py

    - name: Copy resources
      run: |
        cp LICENSE.txt build
        cp schema/*.xsd build/schema
        cp docs/images/* build/images
        mkdir -p build/theme/css
        cp docs/theme/css/*.css build/theme/css
        mkdir -p build/theme/images
        cp docs/theme/images/*.svg build/theme/images
        mkdir -p build/theme/js
        cp docs/theme/js/*.js build/theme/js

    - name: Create ZIP archive
      uses: actions/upload-artifact@v4.4.0
      with:
        name: SSP-Specification
        path: build/*
        if-no-files-found: error

    - name: Check HTML
      uses: zoeleblanc/htmlproofer@master
      with:
        directory: build
        arguments: --only-4xx --url-ignore '/http:\/\/ssp-standard.org\/SSP1\/.*/,/https:\/\/opensource.org\/.*/'

    - name: Push HTML to ssp-standard.org
      if: ${{ github.repository == 'modelica/ssp-standard' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'build'
        destination-github-username: 'modelica'
        destination-repository-name: 'ssp-standard.org'
        user-email: ci@ssp-standard.org
        target-branch: main
        target-directory: static/docs/main
